language: python
sudo: required

before_install: 
  - echo "`date` - travis CI build
  - curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

install:
  - docker-compose up

after_success:
  - echo "docker-compose up successfully"

after_failure:
  - echo "docker-compose up failed"